### PR TITLE
Add the possibility of using this the functional way

### PR DESCRIPTION
**Pull request by roziscoding**
# Proposal
Add possibility to create events and a reducer using pure functions.

## Usage
The functions can be imported as follows:

### Typescript
```ts
/**
 * CommitFunction, EventFactory and Event are helper types
 */
import {
  CommitFunction,
  EventFactory,
  Event,
  createEventFactory,
  createReducer
} from from '@nxcd/tardis/functional'
```

### Javascript
```js
const { createReducer, createEventFactory } = require('@nxcd/tardis/functional')
```

## Examples
Examples of functional usage were added to `/examples/functional` folder

### CODE REVIEW

**Review by khaosdoctor — CHANGES_REQUESTED** [review]
Cool stuff, if you could please update the docs so people can know where are the files and how to use them, then this is good to go

**Comment by roziscoding** [comment]
> Cool stuff, if you could please update the docs so people can know where are the files and how to use them, then this is good to go

Sure. While I'm at it, could you change Codacy rules so they pass for the new JS file? It's asking us to use double quotes and semicolons there

**Comment by khaosdoctor** [comment]
Yeah I've changed it, however it doesn't seem to be resyncing and reanalysing the code. Try to push one more time

**Comment by roziscoding** [comment]
Sure. I'll have to push the docs anyway, so maybe that fixes it

**Comment by khaosdoctor** [comment]
Is this ready to merge?

**Comment by roziscoding** [comment]
@khaosdoctor Nope. The docs are still missing

**Pull request closed without merging**
